drop table if exists player_card CASCADE;
create table player_card (id integer generated by default as identity, age integer not null, football_club varchar(255), player_name varchar(255) not null, player_position varchar(255) not null, primary key (id));

